apiVersion: v1
kind: Service
metadata:
  name: {{ include "spire-registrar.fullname" . }}-controller-manager-metrics-service
  labels:
    app.kubernetes.io/component: kube-rbac-proxy
    app.kubernetes.io/created-by: spire-registar
    app.kubernetes.io/part-of: spire-registar
    control-plane: controller-manager
  {{- include "spire-registrar.labels" . | nindent 4 }}
spec:
  type: {{ .Values.metricsService.type }}
  selector:
    control-plane: controller-manager
  {{- include "spire-registrar.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.metricsService.ports | toYaml | nindent 2 -}}