apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "spire-registrar.fullname" . }}
  labels:
  {{- include "spire-registrar.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.controllerManager.serviceAccount.annotations | nindent 4 }}